#!/usr/bin/env bash

mysqldump -u root -h denwen-teams-production.cm7fec8nnv4c.us-east-1.rds.amazonaws.com -p hasit_production > production.sql

mysql -u root -h denwen-teams-production.cm7fec8nnv4c.us-east-1.rds.amazonaws.com -p hasit_development < production.sql

rm production.sql
