#!/usr/bin/env bash

git fetch
git merge origin/develop
RAILS_ENV=development rake db:migrate
touch tmp/restart.txt
RAILS_ENV=development lib/daemons/processor_ctl stop
RAILS_ENV=development lib/daemons/processor_ctl start
